# Set the build version.
version: "{build}"

# Set the clone folder so that Mutagen ends up in the GOPATH.
clone_folder: C:\gopath\src\github.com\havoc-io\mutagen

# Set Go versions.
environment:
  GOPATH: C:\gopath
  GOROOT: C:\go110
init:
  - set PATH=%GOROOT%\bin;%GOPATH%\bin;%PATH%

# Disable AppVeyor's default Visual Studio build system.
build: off

# Fetch vendored third-party dependencies, install a tool for merging coverage
# profiles, and install the codecov.io Python-based upload tool.
before_test:
  - git submodule init
  - git submodule update
  - pip install codecov

# Run tests, upload the coverage report, and build bundles. We fold coverage
# report uploading into test_script because after_test doesn't seem to fail the
# build if an upload fails (which we want to do).
# TODO: I'd like to run tests for 386 on Windows as well, but it becomes a bit
# more painful since the Windows shell doesn't readily support inline
# environment variables. In any case, we run 386 on Linux and macOS, which
# should be sufficient for the time being.
test_script:
  - go version
  - go test -v -race -coverprofile=coverage.txt ./pkg/...
  - codecov -X gcov -f coverage.txt
  - go run scripts/build.go --mode=testing

# Send notifications.
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
